# Project-level definitions
Main:
  ProjectName: NOAA-Reanalysis
  ProjectHome: /projects/reanalysis/ADCIRC
  ADCIRCHome: /home/bblanton/ADCIRC/v56.dev_da/work
  ExtraTag: "-post"
  Experiment: "post"
  OutputFormat: "netCDF"
  # Processing definitions
  PackageOnly: 0
  DontPrep: 0
  PrepInSubmit: 1
  # submit run to scheduler
  Submit: 1
  # invokes a cleanup script in BinDir/cleanup.sh
  CleanUpDoneRuns: 0 
  CleanUpOnly: 0
  # assumes grid already decomposed (deprecated)
  AssumeDecomp: 0
  ClobberRuns: 0

netCDF:
  title: "NOAA-Reanalysis-Post" 
  institution: "RENCI"
  source: "RENCI_HPC"
  history: "RENCI"
  references: "http://www.renci.org, http://renci.org/reanalysis"
  convention: "CF-UGRID_0.90"
  contact: "Brian_Blanton@Renci.Org"
  basedate: "TBD"   

## ADCIRC/SWAN grid definition (files must be in $GridDir)
Grid:
  Name: "hsofs"
  NameAbbrev: "hsofs"
  Extension: "grd"

MetSource:
  Model: "ERA5"

Fort15:
  #  568   # | 568 etc... 
  IHOT: "0" 
  SpinupLength: "31.0"  # days
  # NTIP if true, compute tidal potential nodal/equilibrium values, 
  # expects <TidalPotentialBlock> as a tag in template file.  If false, 
  # assumes the template fort.15 file takes care of tidal potential.
  NTIP: true
  # NBFR if true, expects to fill <TidalElevationBlock1> and <TidalElevationBlock2>.  If false, assumes template file specifies as needed.
  NBFR: true  
  # Winds
  NWS: "-12"
  # "hbl" | "owi" | "gahm"
  WinPreSrc: "owi" 
  WithBasin: 1
  WithRegion: 0
  BasinPreFile: "fort.221"
  BasinWinFile: "fort.222"
  RegionPreFile: "fort.223"
  RegionWinFile: "fort.224"
  IncludeRivers: 0
  #DRAMP: "7. 0.25 0. 0. 7. 7. 1. 0. <RndayOffset>"
  # forcing rampup length, days
  DRAMP: 15.0 
  # model time step, secs
  DT: 2.0
  # use padcswan (1), or not (0)
  Coupled: 1
  # Output
  StationFile: hsofs.stationfile.dat
  #sets output SPOOLing, secs
  GlobalOutputInterval: 3600.0
  LocalOutputInterval: 3600.0
  RNDAY: 400.0
  TOUTSE: 30.958333333333333
  DynWatLevCor: true

Job:
  Manager: slurm
  NumberOfCores: 512
  NumberOfWriterCores: 2
  ProcessorsPerNode: 1
  Queue: None
  Partition: lowpri
  Reservation: None
  SubmitCommand: sbatch
  StatusCommand: "squeue --noheader --format=\"%i %j %u %C\""
  WallTime: 96:00:00
